### ISSUE TITLE
When the mouse is on the grid, the container can't scroll

### ISSUE THREAD

**Issue by calebkiage** [angular-ui/ng-grid#1926]
Hello, I have disable grid scrolling but when the mouse pointer is in the grid, the container cannot scroll. Any ideas on how I can disable this behavior?

**Comment by PaulL1** [comment]
I believe this is now resolved - could people verify?

**Comment by calebkiage** [comment]
It seems that this has been partially fixed. When scrolling up, the page continues scrolling when the grid's scroller reaches the top which is good. But the same doesn't happen when the grid's scroller is at the bottom. See [102 Sorting](http://ui-grid.info/docs/#/tutorial/102_sorting)
Also, I have noticed that grids don't have enough items to scroll still give issues with scrolling the page. See [101 Intro to UI-Grid](http://ui-grid.info/docs/#/tutorial/101_intro)

**Comment by PaulL1** [comment]
Interesting.  Grids with little data such as the 101 tut allow the page to scroll downwards, but not upwards.  Grids with more data such as 102 sorting allow the page to scroll upwards (when reaching the end of the scroll), but not downwards.

**Comment by PaulL1** [comment]
Thinking further on this, it could be the case that the grid decides whether to scroll itself or propagate to the parent based on how far through the grid scroll it currently is.  If it's 100% and you scroll down, it propagates to the page.  If you're at 0% and you scroll up, it propagates to the page.

So, when you have a grid with less than a page of data, it's always at 100% scroll.  So it won't propagate the scroll up to the page.  And currently we have a miscalculation on the vertical scroll so that when you reach the end of the data, you're not at 100% scroll.  So when you have more than a page of data, currently you maybe cannot get to 100% so that it propagates the scroll down to the parent.

A theory at this stage, no more.

**Comment by joshmackey** [comment]
I'm also getting this problem. I've set the grid to be as tall as needed. We don't want the grid to be scrolling, only the page as a whole. However, whenever the mouse is over the grid, it disabled the whole page scrolling even if the grid itself doesn't scroll any.

**Comment by PaulL1** [comment]
OK, my theory on it not getting to 100% scroll is incorrect, it's a rendering glitch rather than a logic glitch.  That is to say, the scroll bar on my Mac doesn't go all the way to the bottom, but if you look closely it's going all the way to the end of the scroll - perhaps it's leaving space for the horizontal to slide in underneath it?

I can resolve the scrolling on a grid with little data (no scrollbars) by commenting out the `preventDefault`, and it appears to have no impact on anything else.  With the larger grids with scrollbars, I can cause scrolling off the bottom if I "throw" it hard enough, so I still think there's some sort of calculation issue in there.

**Comment by PaulL1** [comment]
Assigning back to @c0bra, where it was before I started playing with it...

**Comment by foxx9** [comment]
+1 Same here , with RC19:
> It seems that this has been partially fixed. When scrolling up, the page continues scrolling when the grid's scroller reaches the top which is good. But the same doesn't happen when the grid's scroller is at the bottom

**Comment by foxx9** [comment]
The issue came back since this commit ( which actually tried to not broke it again) : 
https://github.com/angular-ui/ng-grid/commit/78a4b433b4f186a23a2ec35afe88660f8f361119#commitcomment-9873285

**Comment by tuhoojabotti** [comment]
Also experiencing this on RC21.

**Comment by astreate** [comment]
+1 RC21

**Comment by andreicocari** [comment]
+1 on RC21

**Comment by RazvanCiuca** [comment]
+1 on RC20

**Comment by Rumeth** [comment]
Still experiencing this issue on RC22.

**Comment by Misterhex** [comment]
+1 on RC21

**Comment by kylestev** [comment]
+1 on rc21

**Comment by tufan-yoc** [comment]
+1

**Comment by bartekupartek** [comment]
+1

**Comment by archer-zhn** [comment]
+1

**Comment by tazo90** [comment]
+1 still exists at v3.0.1.

**Comment by naeazach** [comment]
problem persists and i've tried some of the suggested fixes and nothing seems to address it.

**Comment by alejandromagnorsky** [comment]
This still happens in 3.0.7 and is quite annoying for the user. Any solution so far?

**Comment by alejandromagnorsky** [comment]
Actually, I made a solution for my case in particular. In the link function of the directive that wraps the ui-grid I use:
```
$timeout(function () {
    var $viewport = $element.find('.ui-grid-render-container');
    ['touchstart', 'touchmove', 'touchend','keydown', 'wheel', 'mousewheel', 'DomMouseScroll', 'MozMousePixelScroll'].forEach(function (eventName) {
        $viewport.unbind(eventName);
    });
);
```

**Comment by Greynight** [comment]
+1 on 3.0.7

**Comment by vladp5** [comment]
+1 on 3.0.7

**Comment by tuchk4** [comment]
+1 on 3.0.7

**Comment by maitscha** [comment]
+1

**Comment by StevenDewey** [comment]
+1

**Comment by atxabuiro** [comment]
+1

**Comment by Yipyipyip** [comment]
+1

**Comment by andreicocari** [comment]
I also had this problem. I managed to fix it by adding 'ui.grid.autoResize' to my module declaration. Hope it helps.
Cheers,
Andrei Co.

**Comment by shanet** [comment]
I was unable to scroll down when pagination was enabled (although I could scroll up just fine). As a workaround, I added a directive to my table element based off of alejandromagnorsky's solution as follows:

```
  return {
    link: function(scope, element, attr) {
      scope.$watch('isDisplayed', function(newValue, oldValue) {
        var viewport = element.find('.ui-grid-render-container');

        ['touchstart', 'touchmove', 'touchend','keydown', 'wheel', 'mousewheel', 'DomMouseScroll', 'MozMousePixelScroll'].forEach(function (eventName) {
          viewport.unbind(eventName);
        });
      });
    },
  };
```
Scrolling down appears to work now. This was with version 3.0.7.

**Comment by Kamaraju333** [comment]
I still has issue with 3.0.7 scroll doesnt work in chrome

**Comment by vittal288** [comment]
@shanet 
 Why you are unbinding the all events instead it should be bind rt.
Correct if I am wrong here...

**Comment by vittal288** [comment]
The above solution which has given by @shanet  is working in my case...

Thank you so much @shanet

**Comment by nselvidge** [comment]
+1 on 3.1.1

**Comment by piyush-dholariya** [comment]
Still it does not allow me to scroll till bottom of grid,
2nd issue is when I do scrolling upwards/downwards other row seems blinking or looks like removed for while, its not giving smooth scroll.

**Comment by dan2k3k4** [comment]
Which directive did you modify ? Or can I unbind the events inside the `onRegisterApi` function ?

**Comment by piyush-dholariya** [comment]
This issue doesn't seem resolved so it should not be closed.

**Comment by Yoav80** [comment]
+1 , 
i noticed that when i hide the grid headers the outer scroll starts working.. so i guess it has something to do with the calculations of the height of the header..

**Comment by boris-meerovich-sp** [comment]
+1
have the same issue in version 3.1.1

**Comment by stormcrow85** [comment]
+1
none of the above solutions helped in my case
version 3.1.1

**Comment by aviad-chen-sp** [comment]
+1

**Comment by stevejame** [comment]
@alejandromagnorsky   Thank you. You’re so helpful.

**Comment by avim101** [comment]
this is my solution based on @alejandromagnorsky  solution:
ui-grid - v3.1.1
```
(function () {
  'use strict';
  angular.module('myApp')
    .config(function ($provide) {
      $provide.decorator('Grid', function ($delegate,$timeout) {
        $delegate.prototype.renderingComplete = function(){
          if (angular.isFunction(this.options.onRegisterApi)) {
            this.options.onRegisterApi(this.api);
          }
          this.api.core.raise.renderingComplete( this.api );
          $timeout(function () {
            var $viewport =  $('.ui-grid-render-container');
            ['touchstart', 'touchmove', 'touchend','keydown', 'wheel', 'mousewheel', 'DomMouseScroll', 'MozMousePixelScroll'].forEach(function (eventName) {
              $viewport.unbind(eventName);
            });
          });
        };
        return $delegate;
      });
    });

})();
```

that way i dont need to add extra code,watchers,directives and just delegate Grid factory renderingComplete event.

**Comment by avi-meslati-sp** [comment]
select by grid id 
```
(function () {
  'use strict';

  angular.module('siqWeb')
    .config(function ($provide) {
      $provide.decorator('Grid', function ($delegate,$timeout) {
        $delegate.prototype.renderingComplete = function(){
          if (angular.isFunction(this.options.onRegisterApi)) {
            this.options.onRegisterApi(this.api);
          }
          this.api.core.raise.renderingComplete( this.api );
          $timeout(function () {
            var $viewport =  $('#'+this.id+'-grid-container');
            ['touchstart', 'touchmove', 'touchend','keydown', 'wheel', 'mousewheel', 'DomMouseScroll', 'MozMousePixelScroll'].forEach(function (eventName) {
              $viewport.unbind(eventName);
            });
          }.bind(this));
        };
        return $delegate;
      });
    });

})();
```

**Comment by ericsvendsen** [comment]
I've tried unbinding the events as @avim101, @shanet, and @alejandromagnorsky suggested, but it simply doesn't work.  Putting @avim101's example in my app config doesn't do it, and neither does just putting the `forEach` loop inside my controller. My grid is not in a directive.  I can call `$viewport.bind(eventName)` and add whatever I want to the event listener, but it will not unbind.  So frustrating.

I can comment out [this line](https://github.com/angular-ui/ui-grid/blob/master/src/js/core/services/ui-grid-util.js#L1405) in the source and my grid scrolls perfectly, but of course I don't want to modify 3rd party source code.

Anyone have any suggestions or hints regarding placement of the unbind within a regular controller?

**Comment by avim101** [comment]
@ericsvendsen if you can add plunker / github repo we might help you to solve your problem

**Comment by ericsvendsen** [comment]
@avim101 right, my bad. I created a test repository that exhibits this behavior: https://github.com/ericsvendsen/grid-test.

I'm trying to unbind the events [starting on line 209 of gridController](https://github.com/ericsvendsen/grid-test/blob/master/app/modules/gridController.js#L209).

As I say in the readme and in the test app, unbinding seems to work for trackpads, but I can't make it work for mouse scrollwheels.  As long as the cursor is over the grid, the page won't scroll down (the side nav should be long enough unless you're using a 4K monitor). Thanks for offering to have a look.

**Comment by avim101** [comment]
@ericsvendsen 
replace 
```
 .ui-grid, .ui-grid-viewport {
     height: 100%!important;
 }
```
with
```
.ui-grid {
   .ui-grid-viewport {
     height: 100% !important;
   }
 }
```

and you need to calculate grid height dynamically:
http://stackoverflow.com/questions/27837335/angular-ui-grid-dynamically-calculate-height-of-the-grid

**Comment by ericsvendsen** [comment]
@avim101 thanks for the suggestions. I'm grateful you took time to look into my code and offer your help, but it's not a way I want to go right now.  Calculating the grid height dynamically adds ongoing performance overhead to the page and it's just not an ideal solution for me.

I suppose this is where I differ from the angular-ui team, in that I believe a data grid should just show me the rows I ask for, without any weird row virtualization stuff going on, and let the browser scrollbars do their thing.  Any person of sound mind will not show thousands of rows without implementing server-side paging of some sort, and anyone who does, in my opinion, deserves the inevitable performance hit they will encounter from rendering thousands of rows once.

Also, I don't want to change the LESS code as you suggested because I'm trying to follow the solutions put forth in issue #1735, which is where I got that idea from.  And those ideas in that thread seem to work for others, so now the big question was, obviously, why were they not working for me?

Well after a lot of digging, I have discovered the answer.  My app has many different views which contain grids, and after applying what I thought should work to all of them, they all still failed to scroll properly - except for one.  And the difference is that's the only grid in my app that doesn't use the `ui-grid-pagination` directive.  For some reason, the presence of the `.ui-grid-pager-panel` div completely screws everything up.

However, I wasn't even using the built-in pager controls, so I was still confused.  That's when I realized that even if you set `enablePaginationControls` to false, the div is still there because [ui-grid is only using `ng-show` to control that div's visibility](https://github.com/angular-ui/ui-grid/blob/master/src/features/pagination/templates/pagination.html#L5).  Changing it to use `ng-if` and then following @anhkind's suggestion from #1735 solves all my problems.

So now where to go from here?  I can try to remove that div from the DOM manually, which seems to work ok in Chrome, but not Firefox.  So I suppose I will open an issue or submit a PR, and maybe somebody from the team can tell me why they use `ng-show`, or if there is any harm in using `ng-if`.  What would be really great though is if someone could figure out why the `.ui-grid-pager-panel` div causes problems in the first place.

**Comment by roberto326-genebygene** [comment]
@alejandromagnorsky solution worked for me. Thanks!

BTW, I execute the code every time the screen is resized.
```



Actually, I made a solution for my case in particular. In the link function of the directive that wraps the ui-grid I use:

$timeout(function () {
    var $viewport = $element.find('.ui-grid-render-container');
    ['touchstart', 'touchmove', 'touchend','keydown', 'wheel', 'mousewheel', 'DomMouseScroll', 'MozMousePixelScroll'].forEach(function (eventName) {
        $viewport.unbind(eventName);
    });
);
```

**Comment by benjaminW78** [comment]
@avim101  your solution was perfectly clear and worked very well for me thank you ! :+1:

**Comment by avim101** [comment]
@benjaminW78 glad it helped

**Comment by arefaydi** [comment]
for 3.0.6 , I replaced the line on the ui-grid.js
` var mouseWheeltoBind = ( 'onwheel' in document || document.documentMode >= 9 ) ? ['wheel'] : ['mousewheel', 'DomMouseScroll', 'MozMousePixelScroll'],`
 with
`var mouseWheeltoBind = [],`

**Comment by javaScriptCodeer** [comment]
The ui-grid uses (3.1.1) an internal event ($destroy) to unbind all events. 
So I just create an event $destroy in jQuery and trigger it. I do it within the onRegisterApi callback.

var callEventToUnbindMouseEventWhenScroll = function() {
	$timeout(function() {
		var e = jQuery.Event('$destroy');
	        var element = jQuery('.ui-grid-render-container');
		if(element != null) {
			jQuery('.ui-grid-render-container').trigger(e);
		}
	});
};

**Comment by TSkills** [comment]
Using 3.2.9, wheel works up and down when the grid has enableFiltering set to true.
If I don't want any column filter, but still want the wheel to work, I also set enableFiltering to false on each visible column.

**Comment by VincentBlouin** [comment]
I included 'gridUtil' in my directive and I went gridUtil.on.mousewheel = function() {}; It works. Is it ok am I missing something?

**Comment by Odravison** [comment]
The solution from @avim101 worked fine to me :+1:  :confetti_ball: 
Thanks.

**Comment by hey24sheep** [comment]
+1

**Comment by classix-od** [comment]
Maybe this would help someone later:

https://github.com/classix/ui-grid/commit/6285e3f89b47b42a3c53eef4959da8debc87f852
