### ISSUE TITLE
Infinite scroll makes rows disappear when it begins fetching data.

### ISSUE THREAD

**Issue by mikestopcontinues** [angular-ui/ng-grid#2470]
You can see it on the tutorial page:
http://ui-grid.info/docs/#/tutorial/212_infinite_scroll

**Comment by stefansedich** [comment]
I noticed if you scroll up a little then back down when this happens the data appears, anyone have any ideas what it could be?

**Comment by PaulL1** [comment]
@novice3030: I believe you and team added infinite scroll?  Are you getting this issue?

**Comment by stefansedich** [comment]
Has there been any movement on this one? would really like to use this feature!

**Comment by JoaoQuinteira** [comment]
Hey, are there any updates regarding this matter? Would really like to see this solved so I can use it in my company's ongoing projects.  Keep up the good job.

**Comment by PaulL1** [comment]
I believe this was fixed in commit #2730.  Could you retest?

**Comment by cookednoodles** [comment]
The issue is still there unfortunatly, however I feel that its slightly less frequent.

**Comment by JoaoQuinteira** [comment]
I'll give it a test and let you know about the results

**Comment by novice3030** [comment]
Yes we also have this issue
I might get in to it soon
בתאריך 12 בפבר 2015 12:51, ‏"Joao Quinteira" <notifications@github.com> כתב:

**Comment by PaulL1** [comment]
I'm probably going to end up reverting the fix that was done - it has it's fingers too far into core with infinite-scroll specific code.

**Comment by mloutraris-ge** [comment]
Paul, are you thinking of pulling #2730? If so are there any adjustments I can make? I tried to make it infinite scroll specific.

**Comment by PaulL1** [comment]
Yeah, and @swalters correctly pointed out that the core code shouldn't have any knowledge of the features - so it doesn't pass the smell test that we're doing infinite scroll specific stuff in the core.  So we need to work out how to put it into the feature itself, or we need to create a generic function that can be used by any feature, and then call it from infinite scroll.  So yes, I'll need to revert it at some point.

**Comment by mloutraris-ge** [comment]
The scroll adjustment was the difficult part, so I understand. Any idea where this is in the priority list? This infinite scroll is a major piece that we need and we would be willing to help it along in any way that we can.

**Comment by PaulL1** [comment]
For the core team (@swalters, @c0bra, myself), it's not a high priority.  We've decided we can do the 3.0 release without it (marking a few of the features beta).  Our key priorities are fixing scrolling and some alignment issues, and working out what we do with touch devices, which at present seem somewhat fragile.

However, I know there are others who are keen to have the feature working, and we're happy to support that.  It really shouldn't be that difficult in terms of what it does, so I suspect the issues we have aren't actually specific to infinite scroll, but are part of our overall scrolling difficulties.

**Comment by mloutraris-ge** [comment]
Thanks for the response. Infinite scroll is a high priority for us so we will continue to use the code that we have. When you have resolved the general scrolling issues, we can revisit our infinite scroll changes. If you are able to give us that generic function that can we used by any feature, I can own implementing it for infinite scroll.

As an aside, what did you mean by "marking a few of the features beta"? Does that mean you would include infinite scroll (with or without the scroll up) in the product but "use at your own risk"? Just curious.

**Comment by PaulL1** [comment]
Is you suspect, the code would remain in the code base but it would be "use at your own risk".  Which, when you really get down to it, is pretty much the same as all open source code.  :-)  But it would indicate that we thought that code was less "production ready" than the remainder of the grid.

**Comment by mloutraris-ge** [comment]
Sounds good..  Thank You

**Comment by JoaoQuinteira** [comment]
Seems the problem is practically fully gone with this fix. Good job.

**Comment by JoaoQuinteira** [comment]
UPDATE: There is still one small bug. I'm bringing 15 elements each time I need to load more data, and on the second or third time, when the scroll goes up, the rows become blank. However, as soon as I scroll again they appear again. This is more like visual appearance fix. I know this isn't a high prio matter but you could possibly fix it anytime soon.

**Comment by mloutraris-ge** [comment]
That is likely part of the larger scroll/viewport issues. The core team/Paul above mentioned that they are working on getting scrolling issues fixed. Once that is more stable, I plan on revisiting and seeing what I can do to clean up the change I submitted. Getting the correct items viewable was the biggest challenge overall.

**Comment by c0bra** [comment]
This may be fixed with the latest unstable; please check again if you can.

**Comment by cookednoodles** [comment]
This appears finally fixed !

**Comment by c0bra** [comment]
Great!

**Comment by kiran11990** [comment]
What is the property that we need to use in ui-grid for not getting the data removed during the infinite scroll

**Comment by dannymichel** [comment]
+1 ^
