### ISSUE TITLE
All features page is broke

### ISSUE THREAD

**Issue by romcode** [angular-ui/ng-grid#2492]
Hi , 
http://ui-grid.info/docs/#/tutorial/401_AllFeatures
The page is broke, 
there's some errors regarding the percentage of the infinite scroll but i don't think this is the cause for the grid crush .  "Uncaught TypeError: Cannot read property 'percentage' of undefined".
Thanks.

**Comment by PaulL1** [comment]
I think this is now resolved, could you check?

**Comment by romcode** [comment]
It looks that the grid it's still not working.
![error](https://cloud.githubusercontent.com/assets/8833239/5677104/2559a730-97ea-11e4-97e8-253b310ab677.jpg)
But it looks that the infinite scroll it's fixed.
