### ISSUE TITLE
Cell navigation broken in unstable release

### ISSUE THREAD

**Issue by Samy-A** [angular-ui/ng-grid#2658]
Refer to example 202

http://ui-grid.info/docs/#/tutorial/202_cellnav

Navigate down from the first cell. Once you reach the cell with id 11, the focus jumps back to the first cell. (tested in Firefox, Chrome and IE11)

**Comment by Samy-A** [comment]
Thanks @PaulL1

**Comment by PaulL1** [comment]
I think I've tracked this - it's the change we did under #2423.  I'm working on a fix that covers both.

**Comment by PaulL1** [comment]
Fixed this morning I believe - could you retest?

**Comment by Samy-A** [comment]
Thanks, but still something is not working.

Refer again to example 202

http://ui-grid.info/docs/#/tutorial/202_cellnav

In Chrome and IE11, I still get the same as before: once I reach the cell with id 11 it jumps back to the cell with id 1.

In Firefox it is somewhat different. As long as I only navigate down, it works ok.
But, if I navigate down beyond  the cell with id 11, then press once the Arrow Up key, and then start again to navigate down, it also jumps back to the to of the table.

**Comment by PaulL1** [comment]
I'm not getting that at all in Chrome or Safari.  Are you using the arrow key to move down?  I select row 0, then hold down the arrow key, and it scrolls smoothly all the way down.

**Comment by Samy-A** [comment]
In Firefox, when I hold down the arrow key, it scrolls down for a while, and then, apparently randomly, jumps back to the first cell of the first column.
In Chrome, it jumps back to the first cell of the first column after reaching the last visible cell.

**Comment by PaulL1** [comment]
Jumping back to the first cell is expected/designed behaviour when you get to the end - it "wraps around". 

I'll look at my Firefox to see if I get the same behaviour as you there.

**Comment by Samy-A** [comment]
That is wraps around is indeed a nice feature. But in Chrome, it wraps around when reaching the end of the visible region of the table (row 11 in the example). Firefox is less predictable, and mostly works fine, except when I use arrow down, then one arrow up and the arrow down again. Then in also jumps back to the top cell in the first column, regardless of the column I was navigating in.
I also tried to track it in Firebug, but no errors are posted to the console.

**Comment by PaulL1** [comment]
OK, the behaviour you describe in Firefox I can recreate.  Unfortunately I'm only going to have that install for a few more hours, I'm changing locations.  I'll look and see what I can do with it.

**Comment by PaulL1** [comment]
Further diagnosis.  The problem occurs when the grid is scrolled such that the bottommost cell is within the view, but overlaid by the bottom scrollbar.  It looks like scrollToIfNecessary decides it's visible (presumably it's ignoring the scrollbar), and the browser knows better so triggers a native scroll.

The fix I did for scrolling janking when we had a selected cell was that we'd deliberately remove the focus when the scroll didn't come from scrollToIfNecessary.  So the upshot is that we lose focus on the cell in this situation, and then on the next keypress the focus moves to the first cell in the grid.

Two potential solutions.  The first is for scrollToIfNecessary to take the bottom scrollbar into account.  The calculations in there are somewhat scary, and I'm not keen to replicate knowledge that @swalters probably already has.  I'll look.  

The second solution is that it is interestingly scrolling to the correct place (native scroll?), then scrollToIfNecessary moves it back a bit so that the scrollbar overlays the bottom cell.  If it didn't do that the behaviour would be cleaner too.  No doubt both issues have the same source, so not really two solutions.

Lines 624 to 626 of cellNav have a commented out calculation that allows for the horizontal scrollbar.  @swalters may know why.  But here is a plunker with that code reinstated: http://plnkr.co/edit/JkkdV2QWNXsfJPEbNlbg?p=preview

**Comment by Samy-A** [comment]
Yes, that seems to work in both browsers for me too, thanks.

**Comment by Samy-A** [comment]
In my application, I "fixed" the problem by commenting out one line in the post compile function of uiGridRenderContainer:

```javascript
} else {
                    $timeout(function() {
                      // make a dummy roCol
                      var rowCol = { col: { uid: null }, row: { uid: null } };
                          // broadcast a cellNav event so we clear the focus on all cells
                      //uiGridCtrl.cellNav.broadcastCellNav(rowCol);
                    });

```javascript

I commented out the broadcastCellNav command creating a dummy rowCol. 
Of course I'm absolutely not sure that this will not create problem elsewhere.

**Comment by PaulL1** [comment]
The problem that will create is that when you scroll manually with cellNav, it won't correctly handle the focus on the cell.  It will either select a different cell, or sometimes it will break the scrolling entirely.

**Comment by Samy-A** [comment]
Still not working without some hack. Anyway, thanks for the help.

**Comment by PaulL1** [comment]
OK, I think I've fixed this now, at the expense of the focused cell changing whenever you scroll.

**Comment by Samy-A** [comment]
v3.0.0-rc.19 works like a charm!

Many many thanks @PaulL1
