### ISSUE TITLE
Opening expandable grid causes parent grid to collapse when setting width to parent grid columns

### ISSUE THREAD

**Issue by tanak** [angular-ui/ng-grid#2777]
Opening expandable grid causes parent grid to collapse when setting width to parent grid columns. 

![collapsing_grid1](https://cloud.githubusercontent.com/assets/5546638/6186919/95c13430-b3c3-11e4-9b9c-fd6608b67518.png)

![collapsing_grid2](https://cloud.githubusercontent.com/assets/5546638/6186923/9d1b0634-b3c3-11e4-80c8-b461f738aede.png)

I checked this with Chrome, Firefox and IE on Windows.

This is my plunker.
http://plnkr.co/edit/8phKFI0hzfmN7lWK9zMe?p=preview

**Comment by PaulL1** [comment]
When I used your plunker as-is, it didn't do anything for me, and returned errors in attempting to return the rowTemplate.  When I put the rowTemplate inline to avoid this issue, the breakage doesn't occur: http://plnkr.co/edit/DHXXQiQ5tJBNye1l7zQQ?p=preview

Is there a reason you need to retrieve your rowTemplate dynamically?

**Comment by tanak** [comment]
Thank you for checking. I also modified the plunker.

I checked on Chrome in Mac again and found that the problem doesn't occur in a small screen.
It seems that the breakage occurs with larger screen.

Could you use a separate window for preview and check again?

**Comment by PaulL1** [comment]
OK, now I see it.  It isn't breaking the formatting so much, rather what's happened is that the grid is wide enough to fit multiple rows onto a single row (the expanded section is much wider than the core grid).

I presume that means something is messing up the css, I'll look at that.

**Comment by PaulL1** [comment]
This appears resolved on the plunker - could you confirm?

**Comment by tanak** [comment]
I checked with v3.0.0-rc.20-6520046, but expandable seems not to be working with this version.

I also checked the tutorial page, and the result was the same.
http://ui-grid.info/docs/#/tutorial/306_expandable_grid

**Comment by jpuri** [comment]
There have been some issues in the column moving feature in some recent versions. But that should soon be fixed.

**Comment by PaulL1** [comment]
Hmm.  That seems to have broken overnight.  It looks to be fonts, not code - when I check out the code and build and run it, it's fine locally.  It will no doubt come right next time someone pushes something.

**Comment by PaulL1** [comment]
OK, the fonts have been fixed on this for some time, and the plunker no longer exhibits the poor behaviour.  Closing.

**Comment by tanak** [comment]
I was just checking this issue.
This problem still exists, I found that the problem won't occur if there are not so many columns.
So, I added new plunker with many columns.
http://embed.plnkr.co/cchd0s4PFccTmcy1Sn06/preview

Is it better to open new issue?

**Comment by PaulL1** [comment]
@jpuri - have you seen this?

**Comment by jpuri** [comment]
Hi @PaulL1 ,

I checked the issue in the plunkr, it apparently has something to do with the way we handle horizontal scrolling.
I will spend some more time to look into it tomorrow.
