### ISSUE TITLE
Touch event row selection bug

### ISSUE THREAD

**Issue by cookednoodles** [angular-ui/ng-grid#2838]
When selecting a row with UI-Grid in touch mode the registerRowSelectionEvents function is triggering both the touchstart/end and the click events. 

This means that the selectCells function is being called twice, the first time it selects the row, the second time it unselects it.

**Comment by PaulL1** [comment]
@cookednoodles: I think #3142 will address this - is it possible you could look at it and see?

**Comment by PaulL1** [comment]
I think this is now resolved, closing.

**Comment by yuchaozh** [comment]
I still have this problem on mobile(iPhone6) and tablet(Nexus7), sometimes the `rowSelectionChanged()` will be called twice which cause the highlighted selection was changed and it is not what I selected.

Here is my configuration,
 `                
                 enableSorting: true,
                enableRowSelection: true,
                enableRowHeaderSelection: false,
                noUnselect: true,
                multiSelect: false,
`

**Comment by BrutalBrutus** [comment]
I have still see what @yuchaozh posted, on iPad.
