### ISSUE TITLE
uiGrid ~rc.20 Export to PDF in IE

### ISSUE THREAD

**Issue by mathewbeno** [angular-ui/ng-grid#2921]
The pdf export feature is not working in Internet explorer. Does any one else have the same issue?

Thank you

**Comment by PaulL1** [comment]
What version of internet explorer?  What about it doesn't work - are there console errors for example?

I don't have IE, but my usual approach would be to put a breakpoint in the pdfExport method, and step over each line to see which one is failing.  My guess is that the open of the separate window is the thing that's failing, but that's native to pdfMake, so maybe it'll end up as a bug report for them?

**Comment by mathewbeno** [comment]
We are using IE 11.No errors in the console, It opens the second window but it doesn't render any data to the page.

Thank you for your quick response

**Comment by PaulL1** [comment]
Hmm.  Without IE it's hard for me to debug, but it sounds like it's calling the pdfMake method, and then the pdf isn't turning up?

**Comment by c0bra** [comment]
pdfmake doesn't support IE (right now): https://github.com/bpampuch/pdfmake/issues/219#issuecomment-76940824

**Comment by Dev63** [comment]
@c0bra Did pdfmake ever support IE?  I thought it did!  Anyway, is there a way to ask ui-grid to give me the PDF data rather than make a new page?  That way for IE I could create an "echo" service for IE, where I send the data to the server and then launch a new page that opens that data. That's not optimal, but the pdfMake guys are saying that's the only way to "support" IE.  Plus, I have people asking to be able to automatically email the PDF, and I'd need access to the data for that, too.

**Comment by PaulL1** [comment]
It looks to me like we could just call download (or give an option for download instead of open).  
https://github.com/bpampuch/pdfmake/issues/230

**Comment by PaulL1** [comment]
I've pushed code that checks for IE and then calls download instead of open.  I have no ability to test it, so it'd be great if someone could try it out.

**Comment by c0bra** [comment]
@PaulL1 Confirmed, it works for me in IE11. Good job!

Note: the PDF export is still broken in IE, though.

**Comment by PaulL1** [comment]
Oh, what does 'the PDF export is still broken in IE' mean then?  I had thought the thing that was broken was that it didn't open the separate tab, and my impression from the pdfMake repository was that it was the open method that was broken, and that download worked fine.  Is there something else I need to fix?

(it's a bit of a pain not having IE to test with!!)

**Comment by keerthimysa** [comment]
As of Internet Explorer 11, the User Agent String has changed
function toDetectIE() {
    var ua = window.navigator.userAgent;

    var msie = ua.indexOf('MSIE ');
    if (msie > 0) {
        // IE 10 or older => return version number
        return true;
    }

    var trident = ua.indexOf('Trident/');
    if (trident > 0) {
        // IE 11 => return version number
        var rv = ua.indexOf('rv:');
        return true;
    }

    var edge = ua.indexOf('Edge/');
    if (edge > 0) {
       // IE 12 => return version number
       return true;
    }

    // other browser
    return false;
}

**Comment by PaulL1** [comment]
@keerthimysa : any chance of a pull request that adds that code?  I don't have IE to test on, and that code looks partial/indicative only - since it isn't setting version numbers anywhere, and I think we need to both know that it's IE and also know which IE version.  I think the current isIE function was intended to return 0 if not IE, and otherwise return the version number.

**Comment by PaulL1** [comment]
Unfortunately I don't have IE to test on, and that code looks like portions of it are pseudo code, since I can't see where the version number gets returned.

Any chance of a running PR that I can just merge?

**Comment by keerthimysa** [comment]
Sorry, I don't have any pull request that adds the code.
I modified pdfExport function in ui-grid js  to the  below code to work in IE. 
/**
               * @ngdoc function
               * @name pdfExport
               * @methodOf  ui.grid.exporter.service:uiGridExporterService
               * @description Exports rows from the grid in pdf format, 
               * the data exported is selected based on the provided options.
               * Note that this function has a dependency on pdfMake, which must
               * be installed.  The resulting pdf opens in a new
               * browser window.
               * @param {Grid} grid the grid from which data should be exported
               * @param {string} rowTypes which rows to export, valid values are
               * uiGridExporterConstants.ALL, uiGridExporterConstants.VISIBLE,
               * uiGridExporterConstants.SELECTED
               * @param {string} colTypes which columns to export, valid values are
               * uiGridExporterConstants.ALL, uiGridExporterConstants.VISIBLE,
               * uiGridExporterConstants.SELECTED
               */
          pdfExport: function (grid, rowTypes, colTypes) {
                  var exportColumnHeaders = this.getColumnHeaders(grid, colTypes);
                  var exportData = this.getData(grid, rowTypes, colTypes);
                  var docDefinition = this.prepareAsPdf(grid, exportColumnHeaders, exportData);
                  if (this.isIE()) {
                      pdfMake.createPdf(docDefinition).download();
                  } else {
                      pdfMake.createPdf(docDefinition).open();
                  }
              },
              /**
             * @ngdoc function
             * @name isIE
             * @methodOf  ui.grid.exporter.service:uiGridExporterService
             * @description Checks whether current browser is IE and returns true or false
            */
              isIE: function () {
                  var ua = window.navigator.userAgent,
                      msie = ua.indexOf('MSIE '), // IE 10 or older
                      trident = ua.indexOf('Trident/'), // IE 11
                      edge = ua.indexOf('Edge/'); // IE 12
                  if (msie > 0 || trident > 0 || edge > 0) {
                      return true;
                  }
                  // other browser
                  return false;
              },

**Comment by PaulL1** [comment]
I would prefer that the function continues to return a version number, but I don't know the format that it returns currently.

Could you check what it currently returns for the version number - I think it was formatted like '11.0' or something.  Could you then check what value is stored in ua, and whether there's a version number in there?  Ideally we'd have a method that returns `12.0` or `11.1` or whatever.  Otherwise I'm going to end up with two IE detection methods.

**Comment by keerthimysa** [comment]
isIE function needs to be changed to below code to work for both csv and pdf.   

isIE: function () {
                  var match = navigator.userAgent.match(/(?:MSIE |Trident\/.*; rv:)(\d+)/);
                  return match ? parseInt(match[1]) : false;
              },


match value
 [0]: "Trident/7.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; .NET4.0C; .NET4.0E; MS-RTC LM 8; InfoPath.3; rv:11"
    [1]: "11"

**Comment by PaulL1** [comment]
What about edge?

**Comment by keerthimysa** [comment]
Unfortunately, I don't have IE12 to test.

**Comment by c0bra** [comment]
Just want to drop a note here: pdfmake does not support IE currently: https://github.com/bpampuch/pdfmake/issues/219#issuecomment-76940824

**Comment by PaulL1** [comment]
Yeah, I'm separately working on that: https://github.com/bpampuch/pdfmake/issues/16

If I can either get them to return the file as a blob, or get them to implement our same crappy download code, then we would be able to use it on IE.

**Comment by bpampuch** [comment]
Hey @PaulL1 

I'm not sure if it's still relevant, but just to let you know - you can get the file as a blob using the following method:

````javascript
var document = pdfMake.createPdf(docDefinition);

document.getBuffer( function (buffer) {
  blob = new Blob([buffer]);
});
````

**Comment by PaulL1** [comment]
Refer also #3642.  I've implemented this code, which should result in IE getting a PDF downloaded, rather than attempting (and failing) opening the document.  Of course, I don't have IE, so can't actually test it.  :-)

**Comment by c0bra** [comment]
@PaulL1 not working on IE11 w/ latest unstable.

**Comment by c0bra** [comment]
Going to move this up to 3.1 as it seems to be an on-going issue and we need to move on 3.0.

**Comment by PaulL1** [comment]
There's another issue out there with a fix on it I believe - can probably be applied quickly.

**Comment by PaulL1** [comment]
I've applied the fix to #3642, closing this and leaving that open as the master.

**Comment by kushalt** [comment]
I have IE 10 version and getting following error when trying to export data in .pdf

TypeError: Object doesn't support property or method '__defineGetter__'

Any help would be greatly appreciated.
