### ISSUE TITLE
Column Moving Tutorial is broken

### ISSUE THREAD

**Issue by yurigenin** [angular-ui/ng-grid#3131]
When you try to grab and move/drop some columns around you get this exception. You can also notice that sometimes column menu is shown where it is not supposed to.

`TypeError: Cannot read property 'left' of undefined
    at Object.service.repositionMenu (ui-grid-unstable.js:532)
    at ui-grid-unstable.js:636
    at Scope.$emit (angular.js:12916)
    at ui-grid-unstable.js:1873
    at angular.js:14305
    at completeOutstandingRequest (angular.js:4397)
    at angular.js:4705`

**Comment by PaulL1** [comment]
I've done a number of changes on column moving, I think this is now fixed - could you verify?

**Comment by yurigenin** [comment]
No, it is not fixed. Same exceptions in chrome. Plus, after about 10 moves the header being moved becomes thicker and thicker. And it slows down to a crawl. Column menus also pop up and they should not. Just try the tutorial and you will see.

**Comment by PaulL1** [comment]
Did you try the branch with the fixes?  They are not merged to master so wouldn't be on the tutorial pages.

**Comment by PaulL1** [comment]
This is now merged, and the errors are no longer occurring.

**Comment by Bartaf83** [comment]
I've got the same error when trying to open the column header menu : 
```
TypeError: Cannot read property 'left' of undefined
    at Object.repositionMenu (vendors.js?v=6450491eb905:83541)
    at vendors.js?v=6450491eb905:83663
    at vendors.js?v=6450491eb905:29588
    at completeOutstandingRequest (vendors.js?v=6450491eb905:15940)
    at vendors.js?v=6450491eb905:16219
```
ui-grid - v4.0.0
