### ISSUE TITLE
Issue with vertical scroll bar hidding the column data

### ISSUE THREAD

**Issue by AdityaJitu** [angular-ui/ng-grid#3157]
Hi,
Initially when the grid is loaded then the rightmost column is displayed properly.  But when I resize the grid & then the scroll-bar overlaps the contents of the right-most(last) column.
I am attaching the screenshot of the issue that I encountered.

As of now I am using this version.
ui-grid - v3.0.0-RC.18-92a8836 - 2014-12-25
![issue](https://cloud.githubusercontent.com/assets/8811236/6898351/4b07081c-d717-11e4-9743-cb5a4e4099bc.PNG)

I am highlighting the issue.

![issue](https://cloud.githubusercontent.com/assets/8811236/6898373/795587a2-d717-11e4-91a9-34a2b8ebc76e.PNG)

We are showing the scrollbars conditionally using 

enableHorizontalScrollbar:uiGridConstants.scrollbars.WHEN_NEEDED,
enableVerticalScrollbar:uiGridConstants.scrollbars.WHEN_NEEDED

**Comment by yurigenin** [comment]
I do not think WHEN_NEEDED is implemented though. Last time I checked the source code it was not used anywhere.

**Comment by c0bra** [comment]
@AdityaJitu Please update to the latest RC. This has been fixed in versions newer than the one you're using.

**Comment by yurigenin** [comment]
Well, I'm using the latest one and the issue is still there. I do not think it is an issue actually but by design. Unless somebody thinks it is a bug.

**Comment by c0bra** [comment]
@yurigenin The issue should be fixed as of this commit: cf86090f66ee057f Can you reproduce the problem in a plunker?

**Comment by yurigenin** [comment]
Even your tutorials do not work now and the same plunker in the original case has the same behavior. The plunker is using unstable as all your tutorials...

**Comment by c0bra** [comment]
@yurigenin What are you talking about? What plunker? There is no plunker linked in this issue.

What tutorial are you referring to?

**Comment by yurigenin** [comment]
#3138. The original one you closed. There is a plunker there. Go to any tutorial like this:



http://ui-grid.info/docs/#/tutorial/210_selection



And try to use it. Do you see a selection header? Do you see any menus?



That's what I'm talking about.







Thanks,

Yuri

**Comment by c0bra** [comment]
@yurigenin That's a completely separate issue from this one. This issue is about the scrollbar hiding cell contents. Your issue is about icons not being visible on the tutorials. You already filed an issue (four separate issues in fact) for that.

**Comment by yurigenin** [comment]
You are right, it is a separate issue. The issue I was talking about (#3138) was closed before I could test. I added several comments to it asking to reopen but nobody replied. No, my issue is not about icons. My issue is this:




Filter widgets (controls) do not show up if filtering is enabled dynamically #3138



Since nobody replied to my requests to reopen I had to open other ones. Anyway, if you are saying the issue #3138 is resolved, then everything is honky dorky. Except it is not resolved, thus, this thread.




 





 
@yurigenin That's a completely separate issue from this one. This issue is about the scrollbar hiding cell contents. Your issue is about icons not being visible on the tutorials. You already filed an issue (four separate issues in fact) for that.

**Comment by AdityaJitu** [comment]
Hi @c0bra , @yurigenin ,

Thank you for your comments.  I will use the latest release & verify it again.

With Regards,
Aditya Padhi

**Comment by c0bra** [comment]
@yurigenin @AdityaJitu this should be fixed now. Broken tests were preventing the build from completing.

**Comment by AdityaJitu** [comment]
Hi @c0bra ,

It is working fine now.  The issue arises rarely.  I got this issue when I try to resize the browser by dragging the browser edges or by clicking the "restore button" of the browser. It does not happen frequently though.

**Comment by PaulL1** [comment]
Sounds like this is resolved.  Closing.
