### ISSUE TITLE
Grid not loading data in angular bootstrap modal popup window. 

### ISSUE THREAD

**Issue by natarajanmca11** [angular-ui/ng-grid#3616]
Grid not loading data in ui but total count is showing correctly.  Grid looking like below. 
I have tried  $timeout(function () { ...}, 1000)  and $scope.$apply() everything. But no luck. 

![image](https://cloud.githubusercontent.com/assets/9244766/7852625/98c4eb94-0554-11e5-983a-368fcf3759ea.png)

it is loading properly  after Ctrl + scroll action. 

![image](https://cloud.githubusercontent.com/assets/9244766/7852666/6e99f26e-0555-11e5-8a81-b25247f7dce2.png)

Note. I am trying to load this grid inside angular bootstrap Model. 
https://angular-ui.github.io/bootstrap/#/modal

**Comment by PaulL1** [comment]
Could you provide a plunker?  It is logically something different in your code, since this works in the tutorials, but without seeing that code running it's hard to provide input.

**Comment by natarajanmca11** [comment]
Plunker is not working in my machine.. I am working in jsbin. Let you know the url soon... 
Sorry for late reply.

**Comment by natarajanmca11** [comment]
Hi Paul, 
I got the solution for this problem. 
enableRowHeaderSelection  was false. Thats why it was not showing in model popup. I don't know the relationship b/w model popup and this field. other place are working fine without any issue. 

I missed <!DOCTYPE html> attribute on top in index.html file. thats why i got more space to grid header. Now I fixed that problem also. 
Plunker did not work in my machine. anyway, i am fine with this solution. 
Thanks for your support.

**Comment by natarajanmca11** [comment]
I have given the width like  number ,  percentage, and  '*' for auto (as follows.) . In normal screen it shows properly. but in bootstrap modal, initial load its look like shrinked. after Ctrl + scroll, its realigned automatically. 

  columnDefs: [
                  { name: 'id', width: '50' },
                  { name: 'name', width: '20%' },
                  { name: 'age', displayName: 'Age (no focus)', allowCellFocus: false, width: '100' },
                  { name: 'address.city', width: '150' },
                  { name: 'phone', width: '15%' },
                  { name: 'company', width: '100' },
                  { name: 'email', width: '150' },
                  { name: 'balance', width: '100' },
                  { name: 'guid', width: '*' }
                ]

**Comment by PaulL1** [comment]
Bootstrap modal runs an animation on render, and so the point the grid is rendering the modal is not yet full size.  The modal tutorial shows how to use handleWindowResize from a $timeout to deal with this.

**Comment by natarajanmca11** [comment]
Hi Paul,
Yes. This issue is fixed.
Just called the following method.  :)
 $scope.gridApi.grid.handleWindowResize(). 

Thank you Paul.

**Comment by sanjayon19** [comment]
I'm still facing this technical challenge. We have a modal which has UI grid in it. On click of a button we are trying to load the data for Grid. Ajax request is successful, but data is not being displayed on Grid. Only on CTRL+SCROLL or on resize of browser data appears on the Grid. Any suggestion plz?

**Comment by sanjayon19** [comment]
Finally.... Adding 'ui.grid.autoResize' in the angular.module(...) solved this challenge for me.
Thank you :)
