### ISSUE TITLE
When Data is empty getting the following error.

### ISSUE THREAD

**Issue by talasila66** [angular-ui/ng-grid#3973]
When Data is empty getting the following error. Can you please check?

TypeError: Cannot read property 'name' of undefined
    at Grid.buildColumns (ui-grid.js:3890)
    at columnDefsWatchFunction (ui-grid.js:2651)
    at Object.fn (angular.js:15423)
    at m.$digest (angular.js:15556)
    at m.$apply (angular.js:15824)
    at HTMLButtonElement.<anonymous> (angular-touch.js:476)
    at HTMLButtonElement.Gf.c (angular.js:3247)

**Comment by PaulL1** [comment]
What version?  This may have been fixed recently, there was some work done on the data and column defs watches.  If not, could you provide a plunker?

**Comment by talasila66** [comment]
Thank you, Currently using the following version v3.0.0-rc.22.

Will try with latest version, if  the issue still appears will provide the plunker.

**Comment by talasila66** [comment]
Thank you, with latest ui-grid code issue is not reproducing.

Thank you
